# Generated by Django 3.0.8 on 2020-07-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True)),
                ('raca', models.CharField(choices=[('LAB', 'Labrador'), ('BUL', 'Buldogue'), ('POO', 'Poodle'), ('PAS', 'Pastor Alemão'), ('BEA', 'Beagle'), ('GOL', 'Golden Retriever'), ('CHI', 'Chihuahua'), ('HUS', 'Husky Siberiano')], max_length=3)),
                ('idade', models.TextField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
